In [7]:
import numpy as np

In [8]:
X = np.array([[-1, -1],
     [-1, 1],
     [1, -1],
     [1, 1]])

print(X.shape)

Y = np.array([-1, 1, 1, 1])
print(Y.shape)

for x, y in zip(X, Y):
    print(x, " : ", y)

(4, 2)
(4,)
[-1 -1]  :  -1
[-1  1]  :  1
[ 1 -1]  :  1
[1 1]  :  1


In [9]:
rgen = np.random.RandomState(42)

eta = 0.1  # tasa de aprendizaje
w = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1] + 1)
w

array([ 0.00496714, -0.00138264,  0.00647689])

In [10]:
errors = []


In [11]:
def z(x):
    global w

    # print("x=", x)

    z_dot = np.dot(w[1:], x) + w[0]
    # z_sum = w[0]*1 + w[1] * x[0] + w[2]*x[1]
    return z_dot


def predict(x):

    # if z(x) >= 0.0:
    #     return 1
    # else:
    #     return -1
    return np.where(z(x) >= 0.0, 1, -1)

for x in X:
    print(x, " : ", predict(x))

[-1 -1]  :  -1
[-1  1]  :  1
[ 1 -1]  :  -1
[1 1]  :  1


In [12]:
for _ in range(10):
    err = 0
    for xi, target in zip(X, Y):
        output = predict(xi)
        delta = eta * (target - output)

        w[1:] += delta * xi
        w[0] += delta
        print(w)
        err += int(delta != 0.0)
    errors.append(err)

    print("-"*20)

for x in X:
    print(x, " : ", predict(x))

[ 0.00496714 -0.00138264  0.00647689]
[ 0.00496714 -0.00138264  0.00647689]
[ 0.20496714  0.19861736 -0.19352311]
[ 0.20496714  0.19861736 -0.19352311]
--------------------
[0.00496714 0.39861736 0.00647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
--------------------
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
--------------------
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
--------------------
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
--------------------
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
[0.20496714 0.19861736 0.20647689]
--------------------
[0.20496714 0.19861736